### ISSUE TITLE
Clarify that you can't manually listen for the "blocked" action.

### ISSUE THREAD

**Issue by onbjerg** [leonaves/redux-cut#1]
In the README it says:

> The middleware intercepts these actions and instead dispatches a "blocked action" action which you can listen for in your reducer.

However this is not possible, because the prefix for the "blocked" action is not exported in the package. You can only "listen" for it using `isBlockedAction`. This should be clarified.

**Comment by leonaves** [comment]
The dispatched action itself will be a different object each time, i.e.:

``` js
{ 
    type: blockedActionPrefix + originalAction.type,
    payload: originalAction
}
```

Where `originalAction` is the originally dispatched action that is being blocked. However, you're right, the prefix is not exported, this was so that I could change how it worked down the line without breaking the API (using a symbol would probably be the best solution, I will hopefully get to that soon), and it probably could be clearer in the docs. I notice while I've been writing this you've sent a pull request, so I'll take a look at that now...

**Comment by onbjerg** [comment]
It should be in #3
